kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim-02
spec:
  volumeName: pv-hostpath
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi