apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ required "Namespace is required" .Values.deployment.namespace }}
spec:
  ports:
  - port: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: {{ required "Namespace is required" .Values.deployment.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodata
          mountPath: /data/db
      volumes:
      - name: mongodata
        #Only using emptyDir for this simple example. Because volume lifecycle is tied
        #to the pod lifecycle, any data will be lost when the pod is shutdown.
        #For databases, which require durable storage, use network storage volume types.
        emptyDir: {}
