apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secrets
  namespace: {{ required "Namespace is required" .Values.deployment.namespace }}
type: Opaque
data:
  ad_identity_meta_data: {{ .Values.secrets.ad_identity_meta_data  | b64enc }}
  ad_tenant: {{ .Values.secrets.ad_tenant | b64enc }}
  azure_app_id: {{ .Values.secrets.azure_app_id | b64enc }}
  azure_client_secret: {{ .Values.secrets.azure_client_secret | b64enc }}
