apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-ui-config
  namespace: {{ required "Namespace is required" .Values.deployment.namespace }}
data:
  #This value must be the same in ALL config.yaml files!
  is_test_mode: "true"