apiVersion: v1
kind: ConfigMap
metadata:
  name: user-api-config
  namespace: {{ required "Namespace is required" .Values.deployment.namespace }}
data:
  db_url: mongodb://mongodb:27017
  app_log_level: INFO
  is_test_mode: "true"
